load(":target_variants.bzl", "la_variants")
load(":msm_kernel_la.bzl", "define_msm_la")
load(":image_opts.bzl", "boot_image_opts")

target_name = "sun"
target_arch = "sun"

# A16 port: Modules that remain compiled in-tree.
# Many A15 in-tree modules moved to vendor_dlkm prebuilt in A16.
target_arch_in_tree_modules = [
        # keep sorted
        "drivers/base/regmap/qti-regmap-debugfs.ko",
        "drivers/bus/mhi/devices/mhi_dev_satellite.ko",
        "drivers/bus/mhi/devices/mhi_dev_uci.ko",
        "drivers/bus/mhi/host/mhi.ko",
        "drivers/char/rdbg.ko",
        "drivers/clk/clk-scmi.ko",
        "drivers/cpufreq/qcom-cpufreq-hw.ko",
        "drivers/cpufreq/qcom-cpufreq-hw-debug.ko",
        "drivers/cpufreq/qcom-cpufreq-thermal.ko",
        "drivers/crypto/qcom-rng.ko",
        "drivers/devfreq/governor_gpubw_mon.ko",
        "drivers/devfreq/governor_msm_adreno_tz.ko",
        "drivers/dma/qcom/bam_dma.ko",
        "drivers/dma/qcom/msm_gpi.ko",
        "drivers/firmware/arm_scmi/qcom_scmi_vendor.ko",
        "drivers/firmware/qcom-scm.ko",
        "drivers/firmware/qcom/si_core/mem_object.ko",
        "drivers/firmware/qcom/si_core/si_core_module.ko",
        "drivers/firmware/cirrus/cs_dsp.ko",
        "drivers/gpu/drm/bridge/lt9611uxc.ko",
        "drivers/gpu/drm/display/drm_display_helper.ko",
        "drivers/gpu/drm/display/drm_dp_aux_bus.ko",
        "drivers/hwmon/hwmon.ko",
        "drivers/hwmon/qti_amoled_ecm.ko",
        "drivers/hwtracing/coresight/coresight.ko",
        "drivers/hwtracing/coresight/coresight-csr.ko",
        "drivers/hwtracing/coresight/coresight-cti.ko",
        "drivers/hwtracing/coresight/coresight-dummy.ko",
        "drivers/hwtracing/coresight/coresight-funnel.ko",
        "drivers/hwtracing/coresight/coresight-qmi.ko",
        "drivers/hwtracing/coresight/coresight-remote-etm.ko",
        "drivers/hwtracing/coresight/coresight-replicator.ko",
        "drivers/hwtracing/coresight/coresight-stm.ko",
        "drivers/hwtracing/coresight/coresight-tgu.ko",
        "drivers/hwtracing/coresight/coresight-tmc.ko",
        "drivers/hwtracing/coresight/coresight-tmc-sec.ko",
        "drivers/hwtracing/coresight/coresight-tpda.ko",
        "drivers/hwtracing/coresight/coresight-tpdm.ko",
        "drivers/hwtracing/coresight/coresight-trace-noc.ko",
        "drivers/hwtracing/coresight/coresight-uetm.ko",
        "drivers/hwtracing/stm/stm_console.ko",
        "drivers/hwtracing/stm/stm_core.ko",
        "drivers/hwtracing/stm/stm_ftrace.ko",
        "drivers/hwtracing/stm/stm_heartbeat.ko",
        "drivers/hwtracing/stm/stm_p_ost.ko",
        "drivers/i2c/busses/i2c-msm-geni.ko",
        "drivers/i3c/master/i3c-master-msm-geni.ko",
        "drivers/iio/adc/qcom-spmi-adc5-gen3.ko",
        "drivers/iio/adc/qcom-vadc-common.ko",
        "drivers/iio/adc/qti-glink-adc.ko",
        "drivers/input/misc/pm8941-pwrkey.ko",
        "drivers/input/misc/qcom-hv-haptics.ko",
        "drivers/leds/flash/leds-qcom-flash.ko",
        "drivers/leds/leds-qti-flash.ko",
        "drivers/leds/rgb/leds-qcom-lpg.ko",
        "drivers/mfd/qcom-i2c-pmic.ko",
        "drivers/mfd/qcom-spmi-pmic.ko",
        "drivers/misc/qseecom_proxy.ko",
        "drivers/nvmem/nvmem_qfprom.ko",
        "drivers/pci/controller/pci-msm-drv.ko",
        "drivers/power/reset/qcom-dload-mode.ko",
        "drivers/power/reset/qcom-pon.ko",
        "drivers/power/reset/qcom-reboot-reason.ko",
        "drivers/power/reset/reboot-mode.ko",
        "drivers/power/supply/mca/mca_business/business_battery/mca_business_battery_comp.ko",
        "drivers/power/supply/mca/mca_business/business_charger/mca_business_charger_comp.ko",
        "drivers/power/supply/mca/mca_business/business_misc/mca_business_misc_comp.ko",
        "drivers/power/supply/mca/mca_common/mca_adsp_glink.ko",
        "drivers/power/supply/mca/mca_common/mca_common.ko",
        "drivers/power/supply/mca/mca_common/mca_event.ko",
        "drivers/power/supply/mca/mca_common/mca_charge_mievent.ko",
        "drivers/power/supply/mca/mca_common/mca_log.ko",
        "drivers/power/supply/mca/mca_common/mca_parse_dts.ko",
        "drivers/power/supply/mca/mca_common/mca_hwid.ko",
        "drivers/power/supply/mca/mca_common/mca_qcom_smem.ko",
        "drivers/power/supply/mca/mca_common/mca_sysfs.ko",
        "drivers/power/supply/mca/mca_common/mca_charge_interface.ko",
        "drivers/power/supply/mca/mca_common/mca_qcom_panel.ko",
        "drivers/power/supply/mca/mca_common/mca_workqueue.ko",
        "drivers/power/supply/mca/mca_hardware_ic/charge_pump_ic/sc8541/sc8541.ko",
        "drivers/power/supply/mca/mca_hardware_ic/fuelgauge_ic/bq27z561/bq27z561.ko",
        "drivers/power/supply/mca/mca_hardware_ic/wireless_ic/nuvolta_1652/nuvolta_1652.ko",
        "drivers/power/supply/mca/mca_hardware_ic/subpmic/qcom_subpmic/mca_qcom_subpmic_proxy.ko",
        "drivers/power/supply/mca/mca_hardware_ic/boost_ic/hl7603/hl7603.ko",
        "drivers/power/supply/mca/mca_hardware_ic/wireless_ic/sc96281/sc96281_comp.ko",
        "drivers/power/supply/mca/mca_hardware_ic/load_switch_ic/sc7601/sc7601.ko",
        "drivers/power/supply/mca/mca_platform/mca_platform_base.ko",
        "drivers/power/supply/mca/mca_platform/mca_platform_bc12_class.ko",
        "drivers/power/supply/mca/mca_platform/mca_platform_buckchg_class.ko",
        "drivers/power/supply/mca/mca_platform/mca_platform_cp_class.ko",
        "drivers/power/supply/mca/mca_platform/mca_platform_fg_ic_ops.ko",
        "drivers/power/supply/mca/mca_platform/mca_platform_wireless_class.ko",
        "drivers/power/supply/mca/mca_platform/mca_platform_loadsw_class.ko",
        "drivers/power/supply/mca/mca_platform_sysfs/mca_qcom_sysfs.ko",
        "drivers/power/supply/mca/mca_protocol/mca_protocol_class.ko",
        "drivers/power/supply/mca/mca_protocol/protocol_pd/mca_protocol_pd_class.ko",
        "drivers/power/supply/mca/mca_protocol/protocol_pd/qcom_tcpc/qcom_adsp_pd_protocol.ko",
        "drivers/power/supply/mca/mca_protocol/protocol_qc/mca_protocol_qc_class.ko",
        "drivers/power/supply/mca/mca_strategy/mca_strategy_class.ko",
        "drivers/power/supply/mca/mca_hardware_monitor/mca_connector_antiburn.ko",
        "drivers/power/supply/mca/mca_hardware_monitor/mca_bmd.ko",
        "drivers/power/supply/mca/mca_hardware_monitor/mca_path_control.ko",
        "drivers/power/supply/mca/mca_hardware_monitor/mca_lpd_detect.ko",
        "drivers/power/supply/mca/mca_hardware_monitor/mca_vbat_ovp_monitor.ko",
        "drivers/power/supply/mca/mca_hardware_monitor/mca_ibat_ocp_monitor.ko",
        "drivers/power/supply/mca/mca_strategy/strategy_charger/mca_buckchg_jeita.ko",
        "drivers/power/supply/mca/mca_strategy/strategy_charger/mca_charger_thermal.ko",
        "drivers/power/supply/mca/mca_strategy/strategy_charger/mca_strategy_buckchg.ko",
        "drivers/power/supply/mca/mca_strategy/strategy_charger/mca_strategy_quickchg.ko",
        "drivers/power/supply/mca/mca_strategy/strategy_wireless/mca_basic_wireless.ko",
        "drivers/power/supply/mca/mca_strategy/strategy_wireless/mca_wireless_revchg.ko",
        "drivers/power/supply/mca/mca_strategy/strategy_wireless/mca_quick_wireless.ko",
        "drivers/power/supply/mca/mca_strategy/strategy_fg/mca_strategy_fg_class.ko",
        "drivers/power/supply/mca/mca_strategy/strategy_fg/mca_strategy_fg_comp.ko",
        "drivers/power/supply/mca/mca_strategy/strategy_fg/mca_soc_limit.ko",
        "drivers/power/supply/mca/mca_strategy/strategy_pd/mca_pd_auth.ko",
        "drivers/power/supply/mca/mca_smart_charge/mca_smart_charge.ko",
        "drivers/power/supply/mca/mca_shared_memory/charger_partition.ko",
        "drivers/regulator/debug-regulator.ko",
        "drivers/regulator/proxy-consumer.ko",
        "drivers/regulator/qcom-amoled-regulator.ko",
        "drivers/regulator/qti-fixed-regulator.ko",
        "drivers/regulator/qti-ocp-notifier.ko",
        "drivers/remoteproc/qcom_pil_info.ko",
        "drivers/remoteproc/qcom_q6v5.ko",
        "drivers/remoteproc/qcom_q6v5_pas.ko",
        "drivers/remoteproc/qcom_spss.ko",
        "drivers/remoteproc/qcom_sysmon.ko",
        "drivers/remoteproc/rproc_qcom_common.ko",
        "drivers/rpmsg/glink_pkt.ko",
        "drivers/rpmsg/qcom_glink.ko",
        "drivers/rpmsg/qcom_glink_smem.ko",
        "drivers/rpmsg/qcom_glink_spss.ko",
        "drivers/rpmsg/qcom_smd.ko",
        "drivers/rsmc/rsmc_driver.ko",
        "drivers/slimbus/slim-qcom-ngd-ctrl.ko",
        "drivers/slimbus/slimbus.ko",
        "drivers/soc/qcom/adsp_sleepmon.ko",
        "drivers/soc/qcom/altmode-glink.ko",
        "drivers/soc/qcom/boot_stats.ko",
        "drivers/soc/qcom/cdsprm.ko",
        "drivers/soc/qcom/charger-ulog-glink.ko",
        "drivers/soc/qcom/cpucp_log.ko",
        "drivers/soc/qcom/dcvs/bwmon.ko",
        "drivers/soc/qcom/dcvs/c1dcvs_scmi_v2.ko",
        "drivers/soc/qcom/dcvs/cpufreq_stats_scmi_v2.ko",
        "drivers/soc/qcom/dcvs/cpufreq_stats_scmi_v3.ko",
        "drivers/soc/qcom/dcvs/dcvs_fp.ko",
        "drivers/soc/qcom/dcvs/dynpf_scmi.ko",
        "drivers/soc/qcom/dcvs/memlat.ko",
        "drivers/soc/qcom/dcvs/qcom-dcvs.ko",
        "drivers/soc/qcom/dcvs/qcom-pmu-lib.ko",
        "drivers/soc/qcom/dcvs/qcom_scmi_client.ko",
        "drivers/soc/qcom/dmesg_dumper.ko",
        "drivers/soc/qcom/eud.ko",
        "drivers/soc/qcom/fsa4480-i2c.ko",
        "drivers/soc/qcom/glink_probe.ko",
        "drivers/soc/qcom/hung_task_enh.ko",
        "drivers/soc/qcom/llcc_heuristics.ko",
        "drivers/soc/qcom/mem-hooks.ko",
        "drivers/soc/qcom/mem-offline.ko",
        "drivers/soc/qcom/memshare/heap_mem_ext_v01.ko",
        "drivers/soc/qcom/memshare/msm_memshare.ko",
        "drivers/soc/qcom/msm_performance.ko",
        "drivers/soc/qcom/msm_show_epoch.ko",
        "drivers/soc/qcom/panel_event_notifier.ko",
        "drivers/soc/qcom/pdr_interface.ko",
        "drivers/soc/qcom/pmic-glink-debug.ko",
        "drivers/soc/qcom/qti_battery_debug.ko",
        "drivers/soc/qcom/qti_dmof_scmi.ko",
        "drivers/soc/qcom/qti_pmic_glink.ko",
        "drivers/soc/qcom/smp2p.ko",
        "drivers/soc/qcom/smp2p_sleepstate.ko",
        "drivers/soc/qcom/socinfo.ko",
        "drivers/soc/qcom/sps/sps_drv.ko",
        "drivers/soc/qcom/sys_pm_vx.ko",
        "drivers/soc/qcom/sysmon_subsystem_stats.ko",
        "drivers/soc/qcom/tmecom/tmecom-intf.ko",
        "drivers/soc/qcom/wcd_usbss_i2c.ko",
        "drivers/spi/q2spi-geni.ko",
        "drivers/spi/spi-msm-geni.ko",
        "drivers/thermal/qcom/bcl_soc.ko",
        "drivers/thermal/qcom/ddr_cdev.ko",
        "drivers/thermal/qcom/gpu_dump_skip_cdev.ko",
        "drivers/thermal/qcom/max31760_fan.ko",
        "drivers/thermal/qcom/qcom-spmi-temp-alarm.ko",
        "drivers/thermal/qcom/qti_cpufreq_cdev.ko",
        "drivers/thermal/qcom/qti_devfreq_cdev.ko",
        "drivers/thermal/qcom/qti_qmi_cdev.ko",
        "drivers/thermal/qcom/qti_qmi_sensor_v2.ko",
        "drivers/thermal/qcom/qti_userspace_cdev.ko",
        "drivers/thermal/qcom/thermal_config.ko",
        "drivers/tty/serial/msm_geni_serial.ko",
        "drivers/xiaomi/dump_display/dump_display.ko",
        "drivers/xiaomi/swinfo/swinfo.ko",
        "drivers/uio/msm_sharedmem/msm_sharedmem.ko",
        "drivers/usb/dwc3/dwc3-msm.ko",
        "drivers/usb/gadget/function/f_fs_ipc_log.ko",
        "drivers/usb/gadget/function/usb_f_ccid.ko",
        "drivers/usb/gadget/function/usb_f_cdev.ko",
        "drivers/usb/gadget/function/usb_f_gsi.ko",
        "drivers/usb/gadget/function/usb_f_qdss.ko",
        "drivers/usb/host/xhci-sideband.ko",
        "drivers/usb/phy/phy-generic.ko",
        "drivers/usb/phy/phy-msm-m31-eusb2.ko",
        "drivers/usb/phy/phy-msm-snps-eusb2.ko",
        "drivers/usb/phy/phy-msm-ssusb-qmp.ko",
        "drivers/usb/phy/phy-qcom-emu.ko",
        "drivers/usb/redriver/nb7vpq904m.ko",
        "drivers/usb/redriver/redriver.ko",
        "drivers/usb/repeater/repeater.ko",
        "drivers/usb/repeater/repeater-qti-pmic-eusb2.ko",
        "drivers/usb/typec/ucsi/ucsi_qti_glink.ko",
        "kernel/msm_sysstats.ko",
        "kernel/trace/qcom_ipc_logging.ko",
        "net/mac80211/mac80211.ko",
        "net/qrtr/qrtr.ko",
        "net/qrtr/qrtr-mhi.ko",
        "net/qrtr/qrtr-smd.ko",
        "net/qrtr/qrtr-tun.ko",
        "net/wireless/cfg80211.ko",
        "sound/soc/codecs/snd-soc-hdmi-codec.ko",
        "sound/usb/snd-usb-audio-qmi.ko",
        "drivers/misc/hwid/hwid.ko",
]

target_arch_consolidate_in_tree_modules = [
        # keep sorted
        "drivers/cpuidle/governors/qcom_simple_lpm.ko",
        "drivers/hwtracing/coresight/coresight-etm4x.ko",
        "kernel/locking/locktorture.ko",
        "kernel/rcu/rcutorture.ko",
        "kernel/torture.ko",
]

consolidate_board_kernel_cmdline_extras = [
        "console=ttyMSM0,115200n8",
        "qcom_geni_serial.con_enabled=1",
        "earlycon",
        "ufshcd_core.uic_cmd_timeout=2000",
]
consolidate_board_bootconfig_extras = [
        "androidboot.serialconsole=1",
]
consolidate_kernel_vendor_cmdline_extras = [
        "bootconfig",
        "console=ttyMSM0,115200n8",
        "qcom_geni_serial.con_enabled=1",
        "earlycon",
]

perf_board_kernel_cmdline_extras = [ "nosoftlockup console=ttynull qcom_geni_serial.con_enabled=0" ]
perf_board_bootconfig_extras = [ "nosoftlockup console=ttynull qcom_geni_serial.con_enabled=0" ]
perf_kernel_vendor_cmdline_extras = [
        "bootconfig",
        "androidboot.serialconsole=0",
]

def define_sun():
    _sun_in_tree_modules = target_arch_in_tree_modules
    _sun_consolidate_in_tree_modules = _sun_in_tree_modules + target_arch_consolidate_in_tree_modules

    for variant in la_variants:

        if variant == "consolidate":
            mod_list = _sun_consolidate_in_tree_modules
            board_kernel_cmdline_extras = consolidate_board_kernel_cmdline_extras
            board_bootconfig_extras = consolidate_board_bootconfig_extras
            kernel_vendor_cmdline_extras = consolidate_kernel_vendor_cmdline_extras
        else:
            mod_list = _sun_in_tree_modules
            board_kernel_cmdline_extras = perf_board_kernel_cmdline_extras
            board_bootconfig_extras = perf_board_bootconfig_extras
            kernel_vendor_cmdline_extras = perf_kernel_vendor_cmdline_extras

        define_msm_la(
            msm_target = target_name,
            msm_arch = target_arch,
            variant = variant,
            in_tree_module_list = mod_list,
            boot_image_opts = boot_image_opts(
                kernel_vendor_cmdline_extras = kernel_vendor_cmdline_extras,
                board_kernel_cmdline_extras = board_kernel_cmdline_extras,
                board_bootconfig_extras = board_bootconfig_extras,
            ),
        )
